app/books/models.py
from app import db
from marshmallow import Schema, fields, validate
from app.authors.models import AuthorSchema, Author
from flask_sqlalchemy import BaseQuery
from werkzeug.datastructures import MultiDict
from app.utils import convert_string_to_date_format


book_author = db.Table(
    "book_author",
    db.Column(
        "book_id", db.Integer, db.ForeignKey("books.id"), primary_key=True
    ),
    db.Column(
        "author_id", db.Integer, db.ForeignKey("authors.id"), primary_key=True
    ),
)


class Book(db.Model):
    __tablename__ = "books"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    isbn = db.Column(db.BigInteger, nullable=False, unique=True)
    number_of_pages = db.Column(db.Integer, nullable=True)
    published_date = db.Column(db.Date, nullable=True)
    language = db.Column(db.String(2), nullable=False)
    info_link = db.Column(db.String(255), nullable=False)
    authors = db.relationship(
        "Author",
        secondary=book_author,
        lazy="subquery",
        backref=db.backref("books", lazy=True),
    )

    def __repr__(self):
        return f"<{self.__class__.__name__}>: {self.authors}"

    def __str__(self):
        return f"<{self.__class__.__name__}>: {self.authors}"

    def update(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)

    @staticmethod
    def apply_filter(query: BaseQuery, params: MultiDict) -> BaseQuery:
        query = query.join(Author, Book.authors)
        if "author" in params.keys():
            author_value = params["author"]
            if author_value:
                query = query.filter(
                    Book.authors.any(
                        Author.first_and_last_name.ilike(f"%{author_value}%")
                    )
                )

        if "title" in params.keys():
            title_value = params["title"]
            if title_value:
                query = query.filter(Book.title.ilike(f"%{title_value}%"))

        if "language" in params.keys():
            language_value = params["language"]
            if language_value:
                query = query.filter(
                    Book.language.ilike(f"%{language_value}%")
                )

        if "published_date[lte]" in params.keys():
            published_date_lte_value = params["published_date[lte]"]
            if published_date_lte_value:
                query = query.filter(
                    Book.published_date
                    <= convert_string_to_date_format(published_date_lte_value)
                )
        if "published_date[gte]" in params.keys():
            published_date_gte_value = params["published_date[gte]"]
            if published_date_gte_value:
                query = query.filter(
                    Book.published_date
                    >= convert_string_to_date_format(published_date_gte_value)
                )

        return query


class BookSchema(Schema):
    id = fields.Integer(dump_only=True)
    title = fields.String(required=True, validate=validate.Length(max=100))
    isbn = fields.Integer(required=True)
    number_of_pages = fields.Integer(required=True)
    published_date = fields.Date("%Y-%m-%d", required=True)
    language = fields.String(required=True, validate=validate.Length(max=2))
    info_link = fields.String(required=True, validate=validate.Length(max=255))
    authors = fields.Pluck(
        "AuthorSchema",
        "first_and_last_name",
        many=True,
    )
    authors_book = fields.List(fields.String, load_only=True, required=True)


book_schema = BookSchema()

app/books/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    IntegerField,
    FieldList,
    DateField,
    validators,
    FormField,
)
from wtforms.validators import DataRequired, InputRequired, NumberRange
from werkzeug.routing import ValidationError
from app.books.models import Book


class BookForm(FlaskForm):
    title = StringField("Title", validators=[InputRequired()])
    isbn = IntegerField("ISBN", validators=[InputRequired()])
    number_of_pages = IntegerField(
        "Number of pages", validators=[DataRequired()]
    )
    published_date = DateField("Published date", validators=[DataRequired()])
    language = StringField(
        "Language",
        validators=[
            DataRequired(),
            validators.Length(min=2, max=2, message="Użyj 2-literowego skótu"),
        ],
    )
    info_link = StringField("Info link", validators=[DataRequired()])
    authors = FieldList(StringField("Authors"))

    # def validate_isbn(self, field):
    #     check = Book.query.filter(Book.isbn == field.data).first()
    #     if check:
    #         raise ValidationError("Book with this ISBN already exists")
    #     return field.data


# class Unique(object):
#     """ validator that checks ISBN uniqueness """
#     def __init__(self, model, field, message=None):
#         self.model = model
#         self.field = field
#         if not message:
#             message = 'Book with this ISBN already exists'
#         self.message = message
#
#     def __call__(self, form, field):
#         check = self.model.query.filter(self.field == field.data).first()
#         if check:
#             raise ValidationError(self.message)

app/books/__init__.py
from flask import Blueprint

books_bp = Blueprint("books", __name__)

from app.books import models, routes, views, forms

app/books/routes.py
from app.books import books_bp
from app.books.service import BookService
from app.books.models import book_schema
from webargs.flaskparser import use_args
from app.utils import validate_json_content_type


@books_bp.route("/api/v1/books", methods=["GET"])
def get_books():
    return BookService.get_books()


@books_bp.route("/api/v1/books/<int:book_id>", methods=["GET"])
def get_book(book_id: int):
    return BookService.get_book(book_id)


@books_bp.route("/api/v1/books", methods=["POST"])
@validate_json_content_type
@use_args(book_schema, error_status_code=400)
def add_book(args: dict):
    return BookService.add_book(args)


@books_bp.route("/api/v1/books/<int:book_id>", methods=["PUT"])
@validate_json_content_type
@use_args(book_schema, error_status_code=400)
def update_book(args: dict, book_id: int):
    return BookService.update_book(args, book_id)


@books_bp.route("/api/v1/books/<int:book_id>", methods=["DELETE"])
def delete_book(book_id: int):
    return BookService.delete_book(book_id)

app/books/views.py
from app.books import books_bp
from flask import render_template, redirect, flash, request, url_for
from app.books.models import Book
from app import db
from .forms import BookForm
from app.google_api.service import (
    get_books_google_api,
    load_authors,
    load_books,
    google_api_books,
    google_api_authors,
)


def add_edit_book(book_id):
    errors = None
    if book_id is None:
        form = BookForm()
        book = Book(
            title=form.title.data,
            isbn=form.isbn.data,
            number_of_pages=form.number_of_pages.data,
            published_date=form.published_date.data,
            language=form.language.data,
            info_link=form.info_link.data,
            authors=form.authors.data,
        )
    else:
        book = Book.query.filter_by(id=book_id).first_or_404()
        form = BookForm(obj=book)

    if request.method == "POST":
        if form.validate_on_submit():
            if book_id is None:
                db.session.add(book)
                db.session.commit()
                flash("Book has been added")
                return redirect(url_for("books.get_all_books"))
            else:
                form.populate_obj(book)
                db.session.commit()
                flash("Book has been edited")
                return redirect(url_for("books.get_all_books"))
        else:
            errors = form.errors
    return render_template("book_form.html", form=form, errors=errors)


@books_bp.route("/books", methods=["GET", "POST"])
def get_all_books():
    books = Book.apply_filter(Book.query, request.args)
    _books = Book.query.all()
    for book in books:
        authors = ", ".join(map(str, book.authors))
        authors = authors.replace("<Author>:", "")
        book.stringAuthors = authors

    return render_template("books.html", books=books)


@books_bp.route("/new-book", methods=["GET", "POST"])
def add_new_book():
    return add_edit_book(None)


@books_bp.route("/edit/book/<int:book_id>", methods=["GET", "POST"])
def edit_book(book_id):
    return add_edit_book(book_id)


@books_bp.route("/delete/book/<int:book_id>", methods=["POST"])
def delete_single_book(book_id):
    book = Book.query.get(book_id)
    db.session.delete(book)
    db.session.commit()
    flash("Book has been deleted")
    return redirect(request.referrer)


@books_bp.route("/google/books", methods=["GET", "POST"])
def add_google_book():
    if request.method == "POST":
        search_value = request.form.get("search_value")
        print(search_value)
        get_books_google_api(search_value)
        load_authors(google_api_authors)
        load_books(google_api_books)
        flash(
            f"Books from https://www.googleapis.com/books/v1/volumes?q={search_value} have been added"
        )
        return redirect(url_for("books.get_all_books"))

    return render_template("google_api.html")

app/google_api/__init__.py
from flask import Blueprint

google_bp = Blueprint("google", __name__)

from app.google_api import service

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 <meta name="description" content="">
 <title>Book library</title>

 <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">

 <!-- Bootstrap core CSS -->
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
   integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

 <style>
   body {
     padding-top: 5rem;
   }
 </style>
</head>

<body>
 <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
   <a class="navbar-brand" href="/books">Book library</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
     aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarsExampleDefault">
     <ul class="navbar-nav mr-auto">
         <li class="nav-item">
             <a class="nav-link mr-sm" href="/new-book">Add book</a></li>
            <li><a class="nav-link mr-sm" href="/google/books">Google API</a>
         </li>
     </ul>
      <input class="form-control col-lg-1 mr-sm-2" type="text" placeholder="title" aria-label="Search" id="search_title">
      <button class="btn btn-outline-info mr-sm-5" id="search_title_button">Search</button>
       <input class="form-control col-lg-1 mr-sm-2" type="text" placeholder="author" aria-label="Search" id="search_author">
      <button class="btn btn-outline-info mr-sm-5" id="search_author_button">Search</button>
       <input class="form-control col-lg-1 mr-sm-2" type="text" placeholder="language" aria-label="Search" id="search_language">
      <button class="btn btn-outline-info mr-lg-5" id="search_language_button">Search</button>
       <input class="form-control col-lg-2 mr-sm-2 mr-sm-2" type="text" placeholder="published date from"
                    onfocus="(this.type='date')" aria-label="Search" id="search_from">
       <input class="form-control col-sm-2 mr-sm-2 mr-sm-2" type="text" placeholder="published date to"
                    onfocus="(this.type='date')" aria-label="Search" id="search_to">
      <button class="btn btn-outline-info mr-sm-2" id="search_date_button">Search</button>
   </div>
 </nav>

 <main role="main" class="container">

    {% with messages = get_flashed_messages() %}
     {% if messages %}
      {% for message in messages %}
       <div class="alert alert-info mt-3" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
        </button>
       </div>
      {% endfor %}
     {% endif %}
    {% endwith %}

   {% block content %}
   {% endblock %}

 </main><!-- /.container -->
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
   integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
   crossorigin="anonymous"></script>
 <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
   integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
   crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
   integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
   crossorigin="anonymous"></script>

    <script type="text/javascript">

    document.getElementById("search_title_button").onclick = function () {
    const value = document.getElementById("search_title").value;
    location.href = "/books?title=" + value;
    };

    document.getElementById("search_author_button").onclick = function () {
    const value = document.getElementById("search_author").value;
    location.href = "/books?author=" + value;
    };

    document.getElementById("search_language_button").onclick = function () {
    const value = document.getElementById("search_language").value;
    location.href = "/books?language=" + value;
    };

    document.getElementById("search_date_button").onclick = function () {
    const value = document.getElementById("search_from").value;
    const value2 = document.getElementById("search_to").value;
    location.href= "/books?published_date[gte]=" + value + "&published_date[lte]=" + value2;
    };

    </script>

</body>
</html>

app/templates/book_form.html
{% extends "base.html" %}

{% block content %}
<br>
<h3>
   Add new book (under construction :-))
</h3>

<form>
  {{form.hidden_tag()}}
   <div class="form-group">
       <label for="title">Title</label>
       {{ form.title(class_="form-control") }}
   </div>
   <div class="form-group">
       <label for="isbn">ISBN</label>
       {% if errors and errors.isbn %}
           {{ form.isbn(class_="form-control is-invalid") }}
       {% else %}
           {{ form.isbn(class_="form-control") }}
       {% endif %}
       <div class="invalid-feedback">{{ errors.isbn|join(' ') }}</div>
   </div>
    <div class="form-group">
       <label for="number_of_pages">Number of pages</label>
       {{ form.number_of_pages(class_="form-control") }}
   </div>
    <div class="form-group">
       <label for="published_date">Published date</label>
       {{ form.published_date(class_="form-control") }}
   </div>
    <div class="form-group">
       <label for="language">Language</label>
       {{ form.language(class_="form-control") }}
   </div>
    <div class="form-group">
       <label for="info_link">Info link</label>
       {{ form.info_link(class_="form-control") }}
   </div>
<!--    <div class="form-group">-->
<!--       <label for="authors">Authors</label>-->
<!--       {{ form.authors(class_="form-control") }}-->
<!--   </div>-->
   <button type="submit" class="btn btn-primary mt-5">Save</button>
</form>

{% endblock %}

app/templates/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books view</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}

<table class="table">
   <thead>
     <tr>
       <th class="col-2">Title</th>
       <th class="col-1">ISBN</th>
       <th class="col-1">Number of pages</th>
       <th class="col-2">Published date</th>
       <th class="col-1">Language</th>
       <th class="col-1">Info link</th>
       <th class="col-2">Authors</th>
       <th class="col-1"></th>
     </tr>
   </thead>
   <tbody>
       {% for book in books %}
     <tr>
       <td>
           <a href="{{ url_for('books.edit_book', book_id=book.id) }}">
               {{ book.title }}
           </a>
       </td>
       <td>
           {{ book.isbn }}
       </td>
       <td>
           {{ book.number_of_pages }}
       </td>
       <td>
           {{ book.published_date }}
       </td>
       <td>
           {{ book.language }}
       </td>
       <td>
           <a href="{{ book.info_link }}">{{ book.info_link|truncate(20, true) }}</a>
       </td>
       <td>{{ book.stringAuthors }}</td>
        <form action="/delete/book/{{ book.id }}" method="POST">
         <td>
            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
             <button type="submit" class="btn btn-danger">Delete</button>
            </div>
         </td>
        </form>
     </tr>
     {% endfor %}
   </tbody>
 </table>

{% endblock %}
</body>
</html>

app/templates/google_api.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Google API</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}

<br>
<h3>
   Add books from Google API
</h3>
    <form action="/google/books" method="POST">
    <input class="form-control col" type="text" placeholder="e.g Hobbit" aria-label="Search" name="search_value">
      <button type="submit" class="btn btn-primary mt-5">Add</button>
    </form>
{% endblock %}
</body>
</html>